"""empty message

Revision ID: 8437e26c522a
Revises: 330b4f1d634e
Create Date: 2024-05-22 21:39:56.102516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8437e26c522a'
down_revision = '330b4f1d634e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teste', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teste_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teste_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teste', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teste_username'))
        batch_op.drop_index(batch_op.f('ix_teste_email'))

    op.drop_table('teste')
    # ### end Alembic commands ###
